from sentence_transformers import SentenceTransformer

import pandas as pd
import numpy as np
import torch

BUCKET_PATH = "gs://ai_detection/"

df = pd.read_csv(BUCKET_PATH + "complete_with_features.csv")
texts = df['text'].tolist()

print("DATA LOADED - RECORDS:", str(len(df)))

model_name = "instruct"

def get_detailed_instruct(task_description: str, query: str) -> str:
    return f'Instruct: {task_description}\nQuery: {query}'

# Each query must come with a one-sentence instruction that describes the task
task = 'Classify the given text as either generated by an artificial intelligence language model or by a Human author.'

model = SentenceTransformer('intfloat/multilingual-e5-large-instruct', device='cuda')

print("MODEL LOADED")

inputs = [get_detailed_instruct(task,x) for x in texts]

print("INPUT PREPARED")

embeddings = model.encode(inputs)

print("EMBEDDINGS CREATED")

file_name = "Embeddings_" + model_name
np.save(file_name, embeddings)

print("FILE SAVED - EXITING")
